version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  run-test-suite:
    working_directory: ~/databay
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Run all tests
          command: |
            python -m unittest discover test -v


workflows:
  main:
    jobs:
      - run-test-suite
          # filters:
          #   branches:
          #     only:
          #       - dev
          #       - master
